name:                idris-codegen-malfunction
version:             0.1.0.0
github:              "ioanluca/real-world-idris"
license:             BSD3 # FIXME
author:              "Ioan Luca, Stephen Dolan"
maintainer:          "ioan.luca7@gmail.com"
copyright:           "2019 Ioan Luca, Stephen Dolan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ioanluca/real-world-idris#readme>

dependencies:
- base >= 4.7 && < 5
- idris >= 1.3.0
- containers
- process
- directory
- filepath
- text

library:
  source-dirs: src

executables:
  idris-codegen-malfunction:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - idris-codegen-malfunction

tests:
  idris-codegen-malfunction-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - idris-codegen-malfunction
